### PR TITLE
FE-01: setup project for developing

### PR DESCRIPTION
**Pull request by lcnhut**
I've configured all dependency packages for the project. Please check it.
First, you need to checkout to my branch (FE-01) and then run `npm i`. Finally, run `npm run dev`

### CODE REVIEW

**Review by quoctrang-le — APPROVED** [review]
nice bro

**Review by trucho1001 — APPROVED** [review]

**Review by trucho1001 — APPROVED** [review]

**Review by trucho1001 — APPROVED** [review]

**Review by trucho1001 — APPROVED** [review]
Good

**Review by quoctrang-le — APPROVED** [review]
you're doing great

**Comment by quoctrang-le** [comment]
this config will be legendary

**Review by trucho1001 — APPROVED** [review]

**Review by lcnhut — COMMENTED** [review]
Review is done

**Review by trucho1001 — APPROVED** [review]

**Review by quoctrang-le — APPROVED** [review]
good job bro

**Pull request merged**
